---
- name: Set configuration for cli/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/cli/php.ini
    line="{{ item.key }} = {{ item.value }}"
  with_dict: php_cli_config
  when: php_cli_config|length > 0

- name: Set configuration for apache2/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/apache2/php.ini
    line="{{ item.key }} = {{ item.value }}"
  with_dict: php_apache2_config
  when: php_apache2_config|length > 0 and php_webserver == 'apache2'
  notify: restart webserver

- name: Set configuration for fpm/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/fpm/php.ini
    line="{{ item.key }} = {{ item.value }}"
  with_dict: php_fpm_config
  when: php_fpm_config|length > 0 and php_webserver == 'php5-fpm'
  notify: restart webserver
