---
- name: Set default configuration for cli/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/cli/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_default_config
  when: php_default_config|length > 0

- name: Set specific configuration for cli/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/cli/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_cli_config
  when: php_cli_config|length > 0

- name: Set override configuration for cli/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/cli/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_override_config
  when: php_override_config|length > 0

- name: Set default configuration for apache2/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/apache2/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_default_config
  when: php_default_config|length > 0 and php_webserver == 'apache2'
  notify: restart webserver

- name: Set specific configuration for apache2/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/apache2/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_apache2_config
  when: php_apache2_config|length > 0 and php_webserver == 'apache2'
  notify: restart webserver

- name: Set override configuration for apache2/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/apache2/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_override_config
  when: php_override_config|length > 0
  notify: restart webserver

- name: Set default configuration for fpm/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/fpm/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_default_config
  when: php_default_config|length > 0 and php_webserver == 'php5-fpm'
  notify: restart webserver

- name: Set specific configuration for fpm/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/fpm/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_fpm_config
  when: php_fpm_config|length > 0 and php_webserver == 'php5-fpm'
  notify: restart webserver

- name: Set override configuration for fpm/php.ini.
  lineinfile: >
    state=present
    dest=/etc/php5/fpm/php.ini
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_override_config
  when: php_override_config|length > 0 and php_webserver == 'php5-fpm'
  notify: restart webserver

- name: Set fpm settings.
  lineinfile: >
    state=present
    dest=/etc/php5/fpm/pool.d/www.conf
    line="{{ item.key }} = {{ item.value }}"
    regexp="^{{ item.key }} ="
  with_dict: php_fpm_pool_config
  when: php_fpm_pool_config|length > 0 and php_webserver == 'php5-fpm'
  notify: restart webserver
