---
- name: Enable PHP extensions
  command: /usr/sbin/php5enmod {{ item }} creates=/etc/php5/cli/conf.d/20-{{ item }}.ini
  with_items: php_extensions
  sudo: yes
  when: php_extensions | length > 0
  notify: restart webserver